version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/airline_reservation_system
      - JWT_SECRET=your_jwt_secret
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:3000
      - VITE_GOOGLE_AUTH_URL=http://localhost:3000/auth/google
      - VITE_AUTH_URL=http://localhost:3000/auth
      - NODE_OPTIONS=--max-old-space-size=4096
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airline_reservation_system
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

volumes:
  postgres_data:

